# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoe8_XWMt0HCPRLxmDeKs5w1HOroROZW
"""

pip install matplotlib
apt-get install texlive texlive-latex-extra texlive-fonts-recommended dvipng

import subprocess
import os

def render_latex(formula, filename="formula.png", dpi=300):
    """Render LaTeX formula into an image."""
    # Write the formula to a temporary LaTeX file
    with open("temp.tex", "w") as f:
        f.write("\\documentclass[preview]{standalone}\n")
        f.write("\\usepackage{amsmath}\n")  # Add amsmath package for math formatting
        f.write("\\begin{document}\n")
        f.write(formula + "\n")
        f.write("\\end{document}\n")

    # Run the LaTeX command to generate a DVI file
    process = subprocess.run(["latex", "temp.tex"], capture_output=True, text=True)

    # Check if the LaTeX compilation was successful
    if process.returncode != 0:
        print("LaTeX compilation failed with the following output:")
        print(process.stdout)
        print(process.stderr)
        return

    # Check if the .dvi file was created
    if not os.path.exists("temp.dvi"):
        print("No .dvi file created.")
        return

    # Convert the .dvi file to a PNG image
    subprocess.run(["dvipng", "-D", str(dpi), "temp.dvi", "-o", filename])

    # Display the image if possible
    try:
        from PIL import Image
        img = Image.open(filename)
        img.show()
    except Exception as e:
        print(f"Unable to display the image: {e}")
        print(f"Image saved as {filename}")

    # Clean up temporary files
    for file in ["temp.tex", "temp.aux", "temp.dvi", "temp.log"]:
        if os.path.exists(file):
            os.remove(file)

# Example usage
latex_formula = r"\[F={\frac{1}{4\pi\varepsilon_{0}}}{\frac{q q^{\prime}}{r^{2}}}\]"
render_latex(latex_formula)